---
title: "Comparison statistics for NEBULA differential expression results"
author: "Paul Heinrich"
output: 
    html_document:
        toc: true
---

```{r setup1, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Notes

```{r setup2,echo=FALSE, warning=FALSE}
#rbioc_3-14
library(rprojroot)
library(yaml)
library(knitr)

saveSObj <- TRUE

root_criterion <- ".projroot"
proot <- rprojroot::has_file(root_criterion)

source(proot$find_file("experiments/scRNA/analysis/custom/functions/custom_functions.R"))

params <- list()
params$config <- proot$find_file("experiments/scRNA/analysis/custom/hep62703_2023-05-04_B_harmony/config.yaml")
params$analparams <- proot$find_file("experiments/scRNA/analysis/custom/hep62703_2023-05-04_B_harmony/analparams_preprocessing_filters_2023-05-04.yaml")
params$date <- Sys.Date()

config <- yaml.load_file(proot$find_file(params$config))
today <- params$date

print(today)

config <- yaml.load_file(proot$find_file(params$config))
analparams <- yaml.load_file(proot$find_file(params$analparams))

# libraries
libload <- c(
    "Seurat","ggplot2", "harmony", "Nebulosa", "future",
    "WriteXLS", "knitr", "stringr", "dplyr", "foreach", "doParallel"
)

for(i in libload) {
    library(i, character.only = T)
}

plan("multicore", workers = 6)
plan()

# Parallelization with doParallel

registerDoParallel(6)

set.seed(7)

```

```{r loaddata,eval=T,echo=F}

nebulaFit <- readRDS(proot$find_file(config$outputpath, "data", "diff_expr_nebula_cond_cpc-0.005_2023-05-10.rds"))

```

# Compute statistics for comparisons

```{r , eval=T, echo=F}

celltypes <- names(nebulaFit)

treatments <- c(
    "Ctrl" = "logFC_treat_Ctrl",
    "IFNg_IL10" = "logFC_treat_IFNg_IL10",
    "Treg" = "logFC_treat_Treg",
    "Treg_aIL10R" = "logFC_treat_Treg_aIL10R",
    "Treg_aIFNg" = "logFC_treat_Treg_aIFNg",
    "Treg_aIFNg_aIL10R" = "logFC_treat_Treg_aIFNg_aIL10R"
)

combs <- t(apply(combn(treatments, 2), 2, rev))
combNames <- t(apply(combn(names(treatments), 2), 2, rev))
combNames <- paste0(combNames[, 1], "_vs_", combNames[, 2])
rownames(combs) <- combNames
combs <- sapply(rownames(combs), function(x) combs[x, ], simplify = FALSE)
combs <- sapply(combs, function(x) x[!(x %in% "logFC_treat_Ctrl")], simplify = FALSE)

comparisons <- combs

contrasts <- list()

coefIdx <- grep("logFC", colnames(nebulaFit[[1]]$summary))
coefNames <- colnames(nebulaFit[[1]]$summary)[coefIdx]
contrastZeros <- rep(0, length = length(coefNames))
names(contrastZeros) <- coefNames

for (comparison in names(comparisons)) {
    currContrast <- contrastZeros
    currContrast[comparisons[[comparison]][1]] <- 1

    if (length(comparisons[[comparison]]) > 1) {
        currContrast[comparisons[[comparison]][2]] <- -1
    }

    contrasts[[comparison]] <- currContrast
}

comparisonStats <- list()
numberComparisonsTotal <- length(celltypes)*length(comparisons)
comparisonNo <- 1

for (celltype in celltypes) {
    print(paste0("Celltype: ", celltype))
    print(Sys.time())
    genes <- nebulaFit[[celltype]]$summary$gene
    comparisonStats[[celltype]] <- data.frame("gene" = genes)

    for (comparison in names(comparisons)) {
        print(paste0("Comparison: ", comparison))
        print(paste0("Comparison ", comparisonNo, " out of ", numberComparisonsTotal))
        print(Sys.time())
        currStats <- rep(NA, length = length(genes))
        currLogFC <- rep(NA, length = length(genes))
        geneIdx <- 1

        for (gene in comparisonStats[[celltype]]$gene) {
            covMat <- matrix(NA, length(contrastZeros), length(contrastZeros))
            rownames(covMat) <- names(contrastZeros)
            colnames(covMat) <- names(contrastZeros)

            covMat[lower.tri(covMat, diag=T)] <- as.numeric(nebulaFit[[celltype]]$covariance[geneIdx, ])
            covMat[upper.tri(covMat)] <- t(covMat)[upper.tri(covMat)]
            
            currContrast <- contrasts[[comparison]]

            coefDiff <- sum(
                currContrast*nebulaFit[[celltype]]$summary[geneIdx, names(currContrast)]
            )
            currLogFC[geneIdx] <- coefDiff

            pVal <- as.vector(
                pchisq(coefDiff^2/(t(currContrast)%*%covMat%*%currContrast), 1, lower.tail = FALSE)
            )
            currStats[geneIdx] <- pVal

            if (geneIdx%%1000 == 0) {
                print(paste0(geneIdx, " genes covered"))
            }

            geneIdx <- geneIdx + 1
        }

        comparisonStats[[celltype]][[paste0("logFC_", comparison)]] <- currLogFC
        comparisonStats[[celltype]][[paste0("p_", comparison)]] <- currStats

        comparisonNo <- comparisonNo + 1
    }
}

head(nebulaFit$Enterocyte$summary[, grep("^p_", colnames(nebulaFit$Enterocyte$summary))])
head(comparisonStats$Enterocyte[, grep("^p_", colnames(comparisonStats$Enterocyte))])
head(nebulaFit$Enterocyte$summary[, grep("^logFC_", colnames(nebulaFit$Enterocyte$summary))])
head(comparisonStats$Enterocyte[, grep("^logFC_", colnames(comparisonStats$Enterocyte))])

```

```{r save_data, echo=FALSE, warning=FALSE, eval=saveData}

saveRDS(
    comparisonStats,
    proot$find_file(config$outputpath, "data", paste0("stats_nebula_cond_cpc-0.005_", today, ".rds"))
)

```

# SessionInfo

```{r sessionInfo}

sessionInfo()

```

